
export class Pdu {
  public pduId: number;
  public email: string;
  public notes: string;
  public status: string;
  public lastupdate: Date;
  public pdu1: string;
  public pdu2: string;
  public pdu3: string;
  public pdu4: string;
  public pdu5: string;
  public pdu6: string;
  public pdu7: string;
  public pdu8: string;
  public pdu9: string;
  public pdu10: string;
  public pdu11: string;
  public pdu12: string;
  public pdu13: string;
  public pdu14: string;
  public pdu15: string;
  public pdu16: string;
  public pdu17: string;
  public pdu18: string;
  public pdu19: string;
  public pdu20: string;
  public proofpdu1: string;
  public proofpdu2: string;
  public proofpdu3: string;
  public proofpdu4: string;
  public proofpdu5: string;
  public proofpdu6: string;
  public proofpdu7: string;
  public proofpdu8: string;
  public proofpdu9: string;
  public proofpdu10: string;
  public proofpdu11: string;
  public proofpdu12: string;
  public proofpdu13: string;
  public proofpdu14: string;
  public proofpdu15: string;
  public proofpdu16: string;
  public proofpdu17: string;
  public proofpdu18: string;
  public proofpdu19: string;
  public proofpdu20: string;

}
